language: c
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0"

env:
  global:
    - ENABLE_TESTING=OFF

before_install:
    - eval "${MATRIX_EVAL}"
    - test "${CC}" = "gcc"       && ENABLE_TESTING=ON || true
    - test "${CC}" = "clang-5.0" && ENABLE_TESTING=ON || true
    - echo "CC=${CC}"
    - echo "ENABLE_TESTING=${ENABLE_TESTING}"

install:
  # Use clean dependencies installation to avoid versions collision.
  - export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  # Install CMake
  - wget https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh
  - sudo bash cmake-3.10.3-Linux-x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local

before_script:
  # Check installation
  - ${CC} --version
  - cmake --version
  # Configure common CMake options
  - CMAKE_ARGS="-DENABLE_TESTING=${ENABLE_TESTING}"
  - CMAKE_ARGS+=" -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install"
  - echo "CMake arguments ${CMAKE_ARGS}"

script:
  - cmake -H"${TRAVIS_BUILD_DIR}" -B"${TRAVIS_BUILD_DIR}/build" ${CMAKE_ARGS}
  - cmake --build "${TRAVIS_BUILD_DIR}/build" -- -j4
  - if [ "${ENABLE_TESTING}" == "ON" ]; then cmake --build "${TRAVIS_BUILD_DIR}/build" --target test -- ARGS="-VV"; fi

after_success:
  - cmake --build "${TRAVIS_BUILD_DIR}/build" --target install
